from app.agents.base_agent import BaseAgent
from app.models.outputs import ReviewOutput
from app.prompts import REVIEW_PROMPT
from app.services.logger_service import logger


class ReviewerAgent(BaseAgent):
    """
    Reviewer Agent

    Responsibilities
    ----------------
    • Review the outputs generated by all previous agents.
    • Score the paper objectively.
    • Detect missing information.
    • Detect unsupported claims.
    • Recommend improvements.
    • Decide approval.
    """

    def run(
        self,
        analysis: dict,
        summary: dict,
        insights: dict,
    ):

        logger.info("Running Reviewer Agent...")

        prompt = f"""
{REVIEW_PROMPT}

STRICT INSTRUCTIONS

Review ONLY the supplied information.

DO NOT

- invent datasets
- invent experiments
- invent references
- invent results
- invent future work
- invent applications
- use outside knowledge
- search the internet

Your job is to evaluate the QUALITY of the generated outputs.

Evaluation Criteria

1. Completeness
2. Correctness
3. Consistency
4. Missing Information
5. Unsupported Claims
6. Hallucination Detection
7. Readability
8. Structure

Scoring Rules

10 = Excellent

8-9 = Very Good

6-7 = Good

4-5 = Average

0-3 = Poor

Approval Rule

Approved = True

only if

score >= 7

Otherwise

Approved = False

If important information is missing,

mention it in feedback.

Return ONLY valid JSON.

Schema

{{
    "score": 0,
    "feedback": "",
    "approved": false
}}

Analysis

{analysis}

Summary

{summary}

Insights

{insights}
"""

        result = super().run(
            prompt,
            ReviewOutput,
        )

        logger.info(
            f"Reviewer completed. Score: {result.score}"
        )

        return result


reviewer = ReviewerAgent()