from datetime import datetime
from typing import Dict

from pydantic import BaseModel, Field


class FinalReport(BaseModel):
    """
    Final report generated by ResearchMind AI.

    This object is used by:
    - Exporter
    - API
    - Streamlit UI
    - PDF Generator
    """

    title: str = "ResearchMind AI Report"

    created_at: str = Field(
        default_factory=lambda: datetime.now().strftime(
            "%Y-%m-%d %H:%M:%S"
        )
    )

    markdown: str

    report_json: Dict

    quality_score: float = 0.0

    approved: bool = False

    exported_files: Dict = Field(default_factory=dict)